name: firefly_neo_workspace
description: FireflyIII Neo - Personal Finance App Workspace
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dev_dependencies:
  melos: ^6.0.0

